# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      "${builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }}/framework/16-inch/7040-amd"
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/e732018a-166e-4a7b-a3af-214c6eb78acf";
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
  };
  boot.loader.efi.canTouchEfiVariables = true;


  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.hostName = "augustin-Oslandia2";
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp193s0f3u2u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot

  # f16 has a fingerprint reader
  services.fprintd.enable = true;
  # and it can use fwupd, cf https://wiki.nixos.org/wiki/Fwupd
  services.fwupd.enable = true;

  # TODO correct position?
  stylix = {
    enable = true;
# TODO redo that
    image = ./5120x2880.png;
    base16Scheme = "${pkgs.base16-schemes}/share/themes/gruvbox-dark-hard.yaml";
# base16Scheme = "${pkgs.base16-schemes}/share/themes/github.yaml";
    # base16Scheme = {
    #   system = "base16";
    #   name = "Github";
    #   author = "Defman21";
    #   variant = "light";
    #   palette = {
    #     base00 = "ffffff";
    #     base01 = "f5f5f5";
    #     base02 = "c8c8fa";
    #     base03 = "969896";
    #     base04 = "e8e8e8";
    #     base05 = "333333";
    #     base06 = "ffffff";
    #     base07 = "ffffff";
    #     base08 = "ed6a43";
    #     base09 = "0086b3";
    #     base0A = "795da3";
    #     base0B = "183691";
    #     base0C = "183691";
    #     base0D = "795da3";
    #     base0E = "a71d5d";
    #     base0F = "333333";
    #   };
    # };
    cursor = {
      name = "breeze";
      size = 24;
    };
  };
}
