# Inserts a blank line between shell prompts

# currently, when in a nix-shell (?) inside tmux TAB messes up the display with the following line
# add_newline = false
add_newline = true
# default_module_prefix = '<'
# default_module_suffix = '> '

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$gcloud\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""

username.format = '[$user]($style)@'
hostname.format = '[$hostname]($style):'
package.format = '[$symbol$version]($style) ' 
# rust.prefix = 'foo'
