#!/usr/bin/env bash

previewb() {
  colnum=$(tput cols)
  separator=$(eval $(echo printf "_%0.s" {1..$colnum}))
  branch=$(echo $1 | cut -f 1 -d' ' | cut -f1)
  git lg --color=always origin/HEAD..$branch
  echo $separator
  git wd --color=always $branch
}
export -f previewb

git branch -vv --color=always |
  grep --invert-match '\*' |
  cut -c 3- |
  fzf --multi --ansi --preview='bash -c "previewb {}"' |
  while read -r line; do
  git branch --delete --force $(echo $line | cut --delimiter=' ' --field=1)
done
