#!/bin/bash
git branch -vv --color=always |
  grep --invert-match '\*' |
  cut -c 3- |
  fzf --multi --ansi --preview="git lg --color=always {}" |
while read -r line; do
  git branch --delete --force $(echo $line | cut --delimiter=' ' --field=1)
done
