#!/usr/bin/env bash
colnum=$(tput cols)
separator=$(eval $(echo printf '"\-%0.s"' {1..$colnum}))
branch=$(git for-each-ref| grep heads | cut -f2 | cut -d'/' -f3 | fzf --ansi --preview="git w --color=always {1}; echo $separator; git wd --color=always {1}") 
if [ $? == 0 ]; then
  git checkout "$branch"
else 
  exit 1
fi
