#!/usr/bin/env bash
colnum=$(tput cols)
separator=$(eval $(echo printf '"\-%0.s"' {1..$colnum}))
branch=$(git for-each-ref | sed -En 's;^.+heads/(.+)$;\1;p' | fzf --ansi --preview="git lg --color=always origin/HEAD..{1}; echo $separator; git d --color=always origin/HEAD...{1}") 
if [ $? == 0 ]; then
  git checkout "$branch"
else 
  exit 1
fi
